# Prettier Configuration File

# https://prettier.io/docs/en/configuration.html

arrowParens: avoid
bracketSameLine: false
bracketSpacing: false
endOfLine: lf
htmlWhitespaceSensitivity: css
printWidth: 120
proseWrap: preserve
requirePragma: false
semi: true
singleQuote: true
tabWidth: 2
trailingComma: all
useTabs: false
vueIndentScriptAndStyle: true
xmlSelfClosingSpace: false
xmlWhitespaceSensitivity: strict

# Override configuration for certain files
overrides:
  - files: external-links.ditamap
    options:
      printWidth: 80
  - files: source-files.ditamap
    options:
      printWidth: 200
  - files: '*.json'
    options:
      printWidth: 200

plugins:
  - '@prettier/plugin-xml'
